/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct imprimir_operacion_1_argument {
	char *nombre_usuario;
	char *operacion;
	char *nombre_fichero;
	char *timestamp;
};
typedef struct imprimir_operacion_1_argument imprimir_operacion_1_argument;

#define TIMESTAMP_PROG 495775
#define TIMESTAMP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR_OPERACION 1
extern  enum clnt_stat imprimir_operacion_1(char *, char *, char *, char *, int *, CLIENT *);
extern  bool_t imprimir_operacion_1_svc(char *, char *, char *, char *, int *, struct svc_req *);
extern int timestamp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR_OPERACION 1
extern  enum clnt_stat imprimir_operacion_1();
extern  bool_t imprimir_operacion_1_svc();
extern int timestamp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_imprimir_operacion_1_argument (XDR *, imprimir_operacion_1_argument*);

#else /* K&R C */
extern bool_t xdr_imprimir_operacion_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
