/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
timestamp_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *imprimir_operacion_1_nombre_usuario;
	char *imprimir_operacion_1_operacion;
	char *imprimir_operacion_1_nombre_fichero;
	char *imprimir_operacion_1_timestamp;

#ifndef	DEBUG
	clnt = clnt_create (host, TIMESTAMP_PROG, TIMESTAMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = imprimir_operacion_1(imprimir_operacion_1_nombre_usuario, imprimir_operacion_1_operacion, imprimir_operacion_1_nombre_fichero, imprimir_operacion_1_timestamp, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	timestamp_prog_1 (host);
exit (0);
}
