/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_imprimir_operacion_1_argument (XDR *xdrs, imprimir_operacion_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->nombre_usuario, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre_fichero, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, ~0))
		 return FALSE;
	return TRUE;
}
