/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
imprimir_operacion_1(char *nombre_usuario, char *operacion, char *nombre_fichero, char *timestamp, int *clnt_res,  CLIENT *clnt)
{
	imprimir_operacion_1_argument arg;
	arg.nombre_usuario = nombre_usuario;
	arg.operacion = operacion;
	arg.nombre_fichero = nombre_fichero;
	arg.timestamp = timestamp;
	return (clnt_call (clnt, IMPRIMIR_OPERACION, (xdrproc_t) xdr_imprimir_operacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
